# Branch Protection Configuration for Master Branch
# This file documents the recommended branch protection settings

branch_protection:
  master:
    # Require pull request reviews before merging
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
      require_last_push_approval: false
    
    # Require status checks to pass before merging
    required_status_checks:
      strict: true
      contexts: []
    
    # Enforce restrictions
    enforce_admins: false
    allow_force_pushes: false
    allow_deletions: false
    
    # Require linear history
    required_linear_history: true
    
    # Require signed commits (optional)
    require_signed_commits: false
    
    # Lock branch (optional)
    lock_branch: false
    
    # Allow fork syncing
    allow_fork_syncing: true

# Instructions to apply these settings:
# 1. Go to Settings > Branches
# 2. Click "Add rule" for master branch
# 3. Configure the settings as specified above
# 4. Or use GitHub CLI: gh api repos/:owner/:repo/branches/master/protection 